apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-danm-cni-static-ip-controller
  labels:
    app: k8s-danm-cni-static-ip-controller
rules:
- apiGroups: [""]
  resources: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection","nodes"]
  verbs: ["*"]
- apiGroups: ["danm.k8s.io"]
  resources: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection","danmeps","danmnets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments" ,"daemonsets" ,"replicasets","statefulsets"]
  verbs:
  - "*"
- apiGroups: ["extensions"]
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - psp-all
